### ISSUE TITLE
Versions of pre-trained data

### ISSUE THREAD

**Issue by qige96** [thunlp/OpenKE#101]
Hi thunlp members,

So much appreciations to your valuable contributions. I would like to repeat your experiments on Freebase and wikidata, yet I couldn't find out which version of Wikidata dump you used. Could you tell me the exact version of wikidata dump?

**Comment by THUCSTHanxu13** [comment]
The knowledge graphs of Freebase and Wikidata in our experiments can be found in http://139.129.163.161/index/toolkits#pretrained-embeddings. Freebase is the last version, and wikidata is the version in several months ago. We just keep the relations between entities rather than those relations for string values, and keep 60% of the most frequent entities.
