### ISSUE TITLE
Do you know how to add weight on relation path?

### ISSUE THREAD

**Issue by Shane-2015** [thunlp/OpenKE#108]
Hi THUCSTHanxu13,

Do you know how to add weight on relation path?

For example, given a relation path /r1/r2, I would like to add weight1 on r1, and weight2 on r2, so that the relation path became /r1 * weight1/r2 * weight.

Can I change the existing method to make this happen? And do you know which file, which variable I need to change to add the weight on the relation path?

Thank you very much.

regards,
Xianjing

**Comment by THUCSTHanxu13** [comment]
Our package provide platforms for preparing data, training models. If you want to implement your own models, just implement models like existing models (e.g., transE and TransH). Because our platform will input entity ids and relation ids to models, you can set weight for each relation id and use these weights in your own model.
