### ISSUE TITLE
AttributeError: 'str' object has no attribute 'compute_gradients'

### ISSUE THREAD

**Issue by zohreh3906** [thunlp/OpenKE#129]
hello
what is problem? 
![image](https://user-images.githubusercontent.com/37498680/53696617-2556f280-3dde-11e9-8c14-78a911a0e12c.png)

**Comment by mtnntn** [comment]
The problems seems related to the following switch 
https://github.com/thunlp/OpenKE/blob/2f2c26666d5ca08d51f4d146e80718421ad36c51/config/Config.py#L285-L295

I find that it's a problem with the example provided in the example_test_transe.py file. The 'optimizer' variable in this way is directly assigned but, as the first line states, it will skip the assignment of the variable! For testing purpose i think that is not necessary setting an optimizer, so in order to make the example work, just remove the line `con.set_optimizer("SDG")`
