### ISSUE TITLE
Is there any text data document ?

### ISSUE THREAD

**Issue by ldblink** [thunlp/OpenKE#15]
Is there any corresponding text data [such as (ID, entity_context) ] document available for download in order to be able to display the results visually? The data files downloaded from the website (http://openke.thunlp.org) only have IDs. Or I didn't find them. Thanks.

**Comment by THUCSTHanxu13** [comment]
You can find detail information about these entities and relations from Wikidata(https://www.wikidata.org/). More specifically, the web page
(https://www.wikidata.org/wiki/Q2) is about the entity "Q2" and (https://www.wikidata.org/wiki/Property:P361) is about the relation "P361". If you want to download the whole database of Wikidata, you can get the dump from (https://dumps.wikimedia.org/wikidatawiki/entities/).

If you want to map IDs of Freebase entities to their corresponding information, it will be tedious because Freebase is completely shut-down on Aug 31 2016 by Google. You can download the last dump from https://developers.google.com/freebase/ and parse the dump for your need.
