### ISSUE TITLE
input data format - segmentation fault

### ISSUE THREAD

**Issue by FFrankyy** [thunlp/OpenKE#154]
Hi, I prepare my own data and test your code, and met the problem of segmentation fault.

The format is processed followed by your instructions:

train2id.txt: training file, the first line is the number of triples for training. Then the following lines are all in the format (e1, e2, rel) which indicates there is a relation rel between e1 and e2 . Note that train2id.txt contains ids from entitiy2id.txt and relation2id.txt instead of the names of the entities and relations. If you use your own datasets, please check the format of your training file. Files in the wrong format may cause segmentation fault.

And I still get the segmentation fault problem. Do you know why?

One question:  train/test/valid data is separated by '\t' or space?

**Comment by wqh1234** [comment]
I have the same problem as you. How did you solve it

**Comment by shoron-dutta** [comment]
I saw in some comment of an author in another issue that the separator is "\t". I have done that and also created IDs 0~N-1. Still getting segmentation fault error. Please let me know if any of you could solve it.

**Comment by whwang1996** [comment]
> I saw in some comment of an author in another issue that the separator is "\t". I have done that and also created IDs 0~N-1. Still getting segmentation fault error. Please let me know if any of you could solve it.

This may be caused by the type_constrain option is set as True by default. If you haven't run n-n.py for your dataset, there will be no type_constrain.txt file, and will cause segmenation fault while loading data. 
https://github.com/thunlp/OpenKE/blob/7a561c26a13300d910a3253c3efd4fd852f979e0/openke/data/TestDataLoader.py#L27
This can be solved by set option type_constrain to False in TestDataLoader or just run n-n.py for you dataset.

I have also encountered with the same problem, and it really takes me a lot of time to solve it. Hope will be useful for you!
