### ISSUE TITLE
question about running time

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [thunlp/OpenKE#185]
Hello,

Thanks for sharing the code. I have a question regarding the training time. In the paper, the training time of TransE on FB15K for 1000 epochs is about ~300s. However, when I run the example/train_transe_FB15k237.py, each epoch takes roughly 2.2s so in totoal, the running time will be the 2200s, which is about 10 times worse than the time reported in the paper.

I am running it on GTX 1080 so I believe the hardware is pretty good. Am I doing something wrong here?

Thank you.

**Comment by THUCSTHanxu13** [comment]
Can you show me the running scripts. I want to know the hyper-parameter settings.

**Comment by THUCSTHanxu13** [comment]
Besides the GPU, CPU is also important for running time. Because the underlying platform for data processing is run on the CPU with multiple threads. My CPU in experiments is 4GHz, I think the reasons for your time-cost problem may be caused by your CPU. The communication speed between CPU and  GPU on your server may be much slower than my computer.
