### ISSUE TITLE
Could you please provide the detail information of your pretrained embeddings?

### ISSUE THREAD

**Issue by slkingxr** [thunlp/OpenKE#228]
Hi, OpenKE team.Thanks for the amazing open source project. Could you provide more details about your pretrained vectors? For example the TranSE model on wiki data. How do you select/filt the entities/relations ? And what are the configurations you use during training? 
Thanks a lot and happy new year!

**Comment by THUCSTHanxu13** [comment]
For finding a good subset of Wikidata, we first count the frequency of each relation in Wikidata. 
Then, we rank all relations by their frequencies and remove those relations with low frequency. 
Specially, all relations mentioned by fewer than 20 triples are removed by us. 

Because some relations used for keeping the data format of Wikidata, these relations are also removed.  After removing unimportant relations, any triples mention the removed relations are removed. With the above operations, we construct our subset of Wikidata for training pre-trained embeddings.

From our experiments and experience, using DistMult/ComplEx to train a large-scale knowledge graphs is not worthwhile. Some recent works show that other methods (e.g., TransE, ConvE, RotatE) outperform both DistMult and ComplEx on the benchmark dataset. Hence, we use TransE to pre-train the knowledge graph rather than DistMult or ComplEx.

Besides the embeddings, we also provide the knowledge graph used for training. Maybe, you can use our released subset of Wikidata to pretrain DistMult/ComplEx. However, our wikidata comes from the version in two years ago. Maybe you can download a latest version for training.

If you have other problems, please feel free to contact me.
