### ISSUE TITLE
Custom Dataset: Segmentation Fault (core dumped)

### ISSUE THREAD

**Issue by shoron-dutta** [thunlp/OpenKE#287]
Hi,
I have prepared a custom dataset. I went through relevant issues in this repository to find a solution.
I have started the IDs from 0 in entity2id.txt and relation2id.txt files. Also, I have used "\t" as a separator. However, the error is still there.

Is there anything else to look out for in terms of formatting the text files?

FYI: I'm not using type_constrain
Also, correct me if I'm wrong but the tyoe_constrain is an option, not a requirement.
Thank you.

**Comment by NxxTGT** [comment]
same problem

**Comment by whwang1996** [comment]
This may be caused by the type_constrain option is set as True by default. If you haven't run n-n.py for your dataset, there will be no type_constrain.txt file, and will cause segmenation fault while loading data. 
https://github.com/thunlp/OpenKE/blob/7a561c26a13300d910a3253c3efd4fd852f979e0/openke/data/TestDataLoader.py#L27
This can be solved by set option type_constrain to False in TestDataLoader or just run n-n.py for you dataset.

I have also encountered with the same problem, and it really takes me a lot of time to solve it. Hope will be useful for you!

**Comment by BunsenFeng** [comment]
For me, I forgot to add number of entities/relations/triples at the start of data files, which led to the segmentation fault. Hope this is helpful to you!

**Comment by gawainx** [comment]
> This may be caused by the type_constrain option is set as True by default. If you haven't run n-n.py for your dataset, there will be no type_constrain.txt file, and will cause segmenation fault while loading data.
> https://github.com/thunlp/OpenKE/blob/7a561c26a13300d910a3253c3efd4fd852f979e0/openke/data/TestDataLoader.py#L27
> 
> 
> This can be solved by set option type_constrain to False in TestDataLoader or just run n-n.py for you dataset.
> I have also encountered with the same problem, and it really takes me a lot of time to solve it. Hope will be useful for you!

Thank you. I encounter the same problem and your reply help me a lot !

**Comment by dayuyang1999** [comment]
> 

where is the n-n.py file? Thank you.
