### ISSUE TITLE
Necessity of type constraints for validation and testing

### ISSUE THREAD

**Issue by Alekos92** [thunlp/OpenKE#78]
I would like to compliment you for your efforts in the direction of statistical relational learning. 

I would like to ask you about the importance of the type constraints file type_constrain.txt in the testing process. From the introduction to the API, I understand that we only need the validation file to learn thresholds and the testing file to do the actual testing. However, it seems that the type_constrain.txt file is necessary, as its absence leads to a segmentation fault. 

The only way I found to go around this issue in cases where I don't have type constrains is to have a dummy file with the relations followed by no entities. However, this seems more like a hack rather than an actual solution. 

I would appreciate it if you could explain why this file is necessary and how it's exactly used in cases of actual type constraints in my knowledge graph. 

Thank you.

**Comment by ShulinCao** [comment]
Type constraint is used for negative sampling. Let us consider the following example. Suppose we have a ground truth triple LocatedIn(NewOrleans,Louisiana), and corrupt it by replacing its tail entity. First, we remove the tail entity, leaving LocatedIn(NewOrleans,?). Because the relation LocatedIn constraints types of its entities, “?” must be a geographical region. If we fill “?” with a random entity e ∈ E, the probability
of e having a wrong type is very high, resulting in ridiculous triples like LocatedIn(NewOrleans,BarackObama) or LocatedIn(NewOrleans,StarTrek). Such triples are considered
“too easy”, because they can be eliminated solely by types. In contrast, LocatedIn(NewOrleans,Florida)
is a very useful negative triple, because it satisfies type constraints.

**Comment by ShulinCao** [comment]
![image](https://user-images.githubusercontent.com/19309481/44299316-00a99a80-a326-11e8-8985-5627686c2e73.png)
You can get this file through n-n.py.

![image](https://user-images.githubusercontent.com/19309481/44299313-e40d6280-a325-11e8-9dff-c7f1c30ad6c5.png)

**Comment by Alekos92** [comment]
Oh my, I hadn't noticed that!

Thanks for the fast reply, I was off to write my own script to generate the file, but n-n.py does the trick.
