### ISSUE TITLE
Can we add weight on the relation?

### ISSUE THREAD

**Issue by XianjingWang** [thunlp/OpenKE#80]
Hi Cao,

I am wondering if we can add weight on a relation?

Suppose that we have a user viewed one movie _many times_ ('user' as head entity,  '/viewed' as relation, and  'movie' as tail entity),  I want to add a weight on this '/viewed' relation as this user viewed this movie for many times, so that the graph knows that this head has a strong relation with the tail.

Which part of the code shall I edit to add a weight on the relation?

regards,
Xianjing

**Comment by THUCSTHanxu13** [comment]
You can change the sampling function in Config.py so that you can sample training instances and weights at the same time. Then you need to inherit from the "model" class, and build your own model (redefine the loss function) .

**Comment by XianjingWang** [comment]
Thank you very much! I will have a try. 

regards,
Xianjing

**Comment by Shane-2015** [comment]
Hi THUCSTHanxu13,

Do you know how to add weight on relation path?

For example, given a relation path /r1/r2, I would like to add weight1 on r1, and weight2 on r2, so that the relation path became /r1*weight1/r2*weight.

Can I change the existing method to make this happen? And do you know which file, which variable I need to change to add the weight on the relation path?

Thank you very much.

regards,
Xianjing
