### ISSUE TITLE
Windows支持

### ISSUE THREAD

**Issue by Joker-Song** [thunlp/OpenKE#96]
能考虑添加对Windows的支持吗？

**Comment by THUCSTHanxu13** [comment]
Because the current version adopts -pthread to build the underlying code. Because -pthread is not used in Windows, and thus it is difficult to compile our code in Windows. Maybe, you can run the code with Linux or OS X. In the future, we may adopt new underlying designs and support Windows platforms.

**Comment by JinHeap** [comment]
I can run it on windows.need change C++ code in base.and there are something need to be concerned.compile in vs you need sure your platform of python and vs compiler is x64(as my).Then another import things is redefine **INT**  from long to int.I think if you can run simple version https://github.com/thunlp/TensorFlow-TransX on windows then everything is ok

**Comment by Joker-Song** [comment]
> I can run it on windows.need change C++ code in base.and there are something need to be concerned.compile in Visual Studio you need sure your platform of python and vs compiler is x64(as my).Then another import things is redefine **INT** from long to int.I think if you can run simple version https://github.com/thunlp/TensorFlow-TransX on windows then everything is ok

Thank you! I will try it

**Comment by liuhaiying1** [comment]
请问一下为什么config路径下面没有Config.py???

**Comment by liuhaiying1** [comment]
请问一下为什么config路径下面没有Config.py???
