### ISSUE TITLE
Parameters of training models

### ISSUE THREAD

**Issue by yuhaozhang666** [thunlp/OpenKE#98]
Hi,

Can you provide me the parameters when you train TransE, TransH, TransR, TransD and RESCAL?

Thanks!

**Comment by THUCSTHanxu13** [comment]
You can use the code in the folder examples, the code in this folder have essential parameters for training models.

**Comment by yuhaozhang666** [comment]
Are the parameters same for all dataset?

**Comment by Chrixtar** [comment]
Hello,

you probably used other parameters to obtain the results on WN18 stated in your paper.
Could you please provide the optimal parameters, you have found ?
The ones for FB15K are not sufficient.
Otherwise it is hard to compare your results with results of other implementations.

Best regards
Chrixtar
